### ISSUE TITLE
Quarkus native compilation

### ISSUE THREAD

**Issue by dbgjerez** [dbgjerez/workshop-tekton-argocd#1]
When I try to modify the task with following definition: 

```
  - name: native-build
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
      - test
    params:
      - name: MAVEN_IMAGE
        value: 'maven:3-openjdk-17'
      - name: CONTEXT_DIR
        value: $(params.src)
      - name: GOALS
        value: ['clean', 'package', '-Pnative', '-Dquarkus.native.container-build=true']
    workspaces:
      - name: source
        workspace: source
      - name: maven-settings
        workspace: scratch
```

I get an error because the task doesn't contain the possibility to use containers, maybe maven container doesn't have buildha or graalvm to do it
